[package]
name = "aban_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
toml = "0.5.8"
serde = "1.0.130"
serde_derive = "1.0.130"
tinytemplate = "1.2.1"