[package]
name = "aban_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.2.15"
toml = "0.5.8"
cmake = "0.1.46"